### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [diazod/git-prune#17]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by diazod** [comment]
@unixorn [The license](https://github.com/diazod/git-prune/commit/14ea9befe2c7eca98bd3e865c12a013316de95b2) has been added, thanks for the feedback
