### ISSUE TITLE
Y/n misleading

### ISSUE THREAD

**Issue by kwerle** [diazod/git-prune#18]
```
Are you sure you want to delete these branches? (Y/n): 
Are you sure you want to delete these branches? (Y/n): y
```

Because the 'Y' is capitalized, I assume it is the default.  But it does not behave that way.

I would like for it to behave that way (enter means Y).

Thanks for the plugin!

**Comment by diazod** [comment]
The issue should be solved in the new version:
https://github.com/diazod/git-prune/releases/tag/v1.0.1
